services:
  # Backend Service
  - type: web
    name: authentication-website-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://mohit7276:%40Mohit1212@cluster0.ex9i2tk.mongodb.net/authapp?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: SuperSecureJWT2024Key!AuthWebsite
      - key: SESSION_SECRET
        value: SecureSession2024AuthApp!
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 848381710448-ccfoalo5n2id2vn8kmr8i07aj175b8q5.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: FRONTEND_URL
        value: https://authentication-website-frontend.onrender.com

  # Frontend Service  
  - type: web
    name: authentication-website-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://authentication-website-backend.onrender.com
